baseURL = "https://aimtune.dev/"
title = "Hamza Ağar Blog"
theme = ["congo", "reveal-hugo"]

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
hasCJKLanguage = true

params.author.name="Hamza Ağar"
params.author.image="img/hamza2.png"
params.author.bio="Full-stack Developer @DogusTeknoloji"
summaryLength = 70
buildFuture = true

#copyright = "{year}, CC Licences. (Kaynak belirterek paylaşabilirsiniz)"
timeout = 10000
enableEmoji = true
paginate = 15
rssLimit = 100

enableGitInfo = false
googleAnalytics = "G-DBGMJF5XTL"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true
      xHTML = true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true

[taxonomies]
  category = "categories"
  tag = "tags"

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[markup.highlight]
  codeFences = false
  #style = "xcode-dark"
  style = "onedark"
  #style = "github-dark"
  #style = "catppuccin-mocha"

[params.reveal_hugo]
theme = "night"
history = true
slide_number = true
controlsBackArrows = 'faded'
progress = true
showNotes = true
hideInactiveCursor = true
hideCursorTime = 2000
highlight_theme = "vs2015"
margin = 0.2
[params.reveal_hugo.templates.hamza1]
background = "#000002"
transition = "convex"
[params.reveal_hugo.templates.hamza2]
background = "#0a274e"
transition = "convex"
[params.reveal_hugo.templates.hamza3]
background = "#3658a3"
transition = "convex"
[params.reveal_hugo.templates.hamza4]
background = "#708eff"
transition = "convex"
[params.reveal_hugo.templates.hamza5]
background = "#bbc9ff"
transition = "convex"
[params.reveal_hugo.templates.blue]
background = "#0011DD"
transition = "zoom"
[params.reveal_hugo.templates.hamzadark1]
background = "#141021"
[params.reveal_hugo.templates.hamzadark2]
background = "#3c3557"
[params.reveal_hugo.templates.hamzadark3]
background = "#736494"
[params.reveal_hugo.templates.hamzadark4]
background = "#c099de"
[params.reveal_hugo.templates.hamzadark5]
background = "#f8cbed"
[params.reveal_hugo.templates.darkslide1]
background = "#000000"  # Saf Siyah
[params.reveal_hugo.templates.darkslide2]
background = "#0a0a0f"  # Neredeyse Siyah (Hafif Gri-Mor Alt Ton)
[params.reveal_hugo.templates.darkslide3]
background = "#12121c"  # Çok Koyu Gri-Mor
[params.reveal_hugo.templates.darkslide4]
background = "#1a1a28"  # Siyaha Yakın Duman Moru
[params.reveal_hugo.templates.darkslide5]
background = "#222236"  # Derin Kömür Moru
[params.reveal_hugo.templates.darkslide6]
background = "#2c2944"  # Füme Erik Tonu
[params.reveal_hugo.templates.darkslide7]
background = "#383354"  # Koyu Lavanta
[params.reveal_hugo.templates.darkslide8]
background = "#453c65"  # Derin Menekşe
[params.reveal_hugo.templates.darkslide9]
background = "#524576"  # Koyu Eflatun
[params.reveal_hugo.templates.darkslide10]
background = "#64538e"  # Yumuşayan Lavanta Moru
[params.reveal_hugo.templates.darkslide11]
background = "#79689f"  # Hafif Lavanta
[params.reveal_hugo.templates.darkslide12]
background = "#907eb5"  # Pastel Lila
[params.reveal_hugo.templates.darkslide13]
background = "#a78dbf"  # Açık Lavanta Tonu
[params.reveal_hugo.templates.darkslide14]
background = "#c4a9db"  # Açık Leylak
[params.reveal_hugo.templates.darkslide15]
background = "#e6c8ef"  # Parlak Pastel Pembe