[en]
title = "Hamza Agar"
languageName = "English"
weight = 1
languageDirection = "ltr"
skills = "Skills"
work_experience = "Work Experience"
education = "Education"
projects = "Projects"
contact = "Contact"
about = "About"
primary_tools = "Primary Tools"
experienced_technologies = "Experienced Technologies"
currently_learning = "Currently Learning"
website = "Website"
source = "Source"
contact_text = "Feel free to reach out to me for any inquiries or opportunities."
profile_subtitle = "Associate Specialist Software Developer"
greeting = "Hi, I'm"

[en.params.author]
name = "Hamza Agar"
only_name = "Hamza"
surname = "Agar"
#image = "hamza.jpg"
headline = "Associate Specialist Software Developer [**@DogusTeknoloji**](https://www.d-teknoloji.com.tr/)"
bio = "Associate Specialist Software Developer"
links = [
  { linkedin = "https://linkedin.com/in/hamzaagar" },
  { github = "https://github.com/aimtune" },
  { x-twitter = "https://twitter.com/aimtune" },
  { email = "mailto:hamzaagareng@gmail.com" },
  { rss = "/en/index.xml" },
  #   { link = "https://link-to-some-website.com/" },
  #   { discord = "https://discord.gg/invitecode" },
  #   { dribbble = "https://dribbble.com/username" },
  #   { google-scholar = "https://scholar.google.com/citations?user=user-id" },
  #   { instagram = "https://instagram.com/username" },
  #   { medium = "https://medium.com/username" },
  #   { orcid = "https://orcid.org/userid" },
  #   { slack = "https://workspace.url/team/userid" },
  #   { stack-overflow = "https://stackoverflow.com/users/userid/username" },
  #   { steam = "https://steamcommunity.com/profiles/userid" },
  #   { telegram = "https://t.me/username" },
  #   { tiktok = "https://tiktok.com/@username" },
  #   { tumblr = "https://username.tumblr.com" },
  #   { twitch = "https://twitch.tv/username" },
  #   { whatsapp = "https://wa.me/phone-number" },
  #   { youtube = "https://youtube.com/username" },
]