[en]
  title = "Hamza Agar"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[tr]
  title = "Hamza Ağar"
  languageName = "Türkçe"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/tr"