[[main]]
  identifier = "about"
  name = "Hakkımda"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Arşiv"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "Sunum"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "Galeri"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Karikatür"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Fotoğraf"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Yazılar"
  url = "posts"
  weight = 5

[[main]]
  identifier = "showcase"
  name = "Projelerim"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "Makalelerim"
  url = "publication"
  weight = 7