[[main]]
name = "Hakkımda"
pageRef = "about"
weight = 1

[[main]]
name = "Bloglar"
pageRef = "posts"
weight = 2

[[main]]
name = "Sunumlar"
pageRef = "presentations"
weight = 3

[[main]]
name = "Portfolyo"
pageRef = "showcase"
weight = 4

[[main]]
name = "Makaleler"
pageRef = "publications"
weight = 5

[[main]]
identifier = "search"
weight = 99
[main.params]
action = "search"

[[main]]
identifier = "locale"
weight = 100
[main.params]
action = "locale"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
name = "Etiketler"
pageRef = "tags"
weight = 10
