[tr]
  title = "Hamza Ağar"
  languageName = "Türkçe"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/tr"
  
[en]
  title = "Hamza's Blog"
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/en"