version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_temp_data:/home/tempdata
    networks:
      - n8n_network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: RabbitMQ
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - n8n_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

volumes:
  n8n_data:
  rabbitmq_data:
networks:
  n8n_network:
    driver: bridge
